name: "Release new version"
on:
  workflow_run:
    workflows:
      - "CI Tests"
    branches:
      - master
    types:
      - completed
jobs:
  github:
    name: "Create GitHub Release"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
      - name: "Get version"
        run: echo "PLUGIN_VERSION=$(cat streamflow/plugins/unito/postgresql/version.py | grep -oP '(?<=VERSION = \")(.*)(?=\")')" >> $GITHUB_ENV
      - name: "Check tag existence"
        uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with:
          tag: ${{ env.PLUGIN_VERSION }}
      - name: "Create Release"
        id: create-release
        uses: actions/create-release@v1
        if: ${{ steps.check-tag.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PLUGIN_VERSION }}
          release_name: ${{ env.PLUGIN_VERSION }}
          draft: false
          prerelease: false
  pypi:
    name: "Publish on PyPI"
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/project/streamflow-postgresql
    permissions:
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: "Get local version"
        run: echo "PLUGIN_VERSION=$(cat streamflow/plugins/unito/postgresql/version.py | grep -oP '(?<=VERSION = \")(.*)(?=\")')" >> $GITHUB_ENV
      - name: "Get PyPI version"
        run: echo "PYPI_VERSION=$(pip index versions --pre streamflow-postgresql | grep streamflow-postgresql | sed 's/.*(\(.*\))/\1/')" >> $GITHUB_ENV
      - name: "Build Python packages"
        if: ${{ env.PLUGIN_VERSION != env.PYPI_VERSION }}
        run: |
          python -m pip install build --user
          python -m build --sdist --wheel --outdir dist/ .
      - name: "Publish package to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ env.PLUGIN_VERSION != env.PYPI_VERSION }}
